portada:
    path:    /{ciudad}
    defaults:    { _controller: OfertaBundle:Default:portada }

_portada:
    path:    /
    defaults:    { _controller: FrameworkBundle:Redirect:redirect, route: portada, ciudad: '%cupon.ciudad_por_defecto%' }

ciudad_recientes:
    path:    /{ciudad}/recientes
    defaults:    { _controller: CiudadBundle:Default:recientes }

usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

tienda:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /

ciudad:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /

oferta:
    path:    /{ciudad}/ofertas/{slug}
    defaults:    { _controller: OfertaBundle:Default:oferta}

pagina_estatica:
    path:    /sitio/{pagina}/
    defaults:    { _controller: OfertaBundle:Sitio:estatica }

